-- create database with required field

CREATE TABLE movies(  
  MOVIE_ID INTEGER PRIMARY KEY NOT NULL,  
  TITLE VARCHAR(200) NOT NULL,  
  RATING float(2,1) NOT NULL, 
  TOTAL_VOTES INT NOT NULL, 
  GENRE1 VARCHAR(100) NOT NULL, 
  GENRE2 VARCHAR(100) NOT NULL, 
  GENRE3 VARCHAR(100) NOT NULL, 
  META_CRITIC TINYINT NOT NULL, 
  BUDGET VARCHAR(100) NOT NULL, 
  RUNTIME VARCHAR(100) NOT NULL
);  